# Generated by Django 5.1.7 on 2026-09-20 14:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SmartDirectSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("instagram_user_id", models.CharField(db_index=True, max_length=64)),
                ("external_conversation_id", models.CharField(blank=True, db_index=True, max_length=128)),
                ("started_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("last_activity_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("LINK_SENT", "Link sent"),
                            ("ADMIN_HANDOFF", "Admin handoff"),
                            ("CLOSED", "Closed"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=32,
                    ),
                ),
                ("request_summary", models.TextField(blank=True)),
                ("detected_product_type", models.CharField(blank=True, max_length=255)),
                ("detected_color", models.CharField(blank=True, max_length=128)),
                ("detected_size", models.CharField(blank=True, max_length=64)),
                ("detected_budget_min", models.BigIntegerField(blank=True, null=True)),
                ("detected_budget_max", models.BigIntegerField(blank=True, null=True)),
                ("selected_product_source_id", models.BigIntegerField(blank=True, null=True)),
                ("selected_variant_source_id", models.BigIntegerField(blank=True, null=True)),
                ("outcome", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "db_table": "smart_direct_sessions",
                "ordering": ["-last_activity_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SmartDirectEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("SESSION_STARTED", "Session started"),
                            ("PRODUCT_REQUEST", "Product request"),
                            ("PRODUCT_SUGGESTED", "Product suggested"),
                            ("PRODUCT_SELECTED", "Product selected"),
                            ("PRODUCT_LINK_SENT", "Product link sent"),
                            ("LINK_CLICKED", "Link clicked"),
                            ("ADMIN_HANDOFF", "Admin handoff"),
                            ("SESSION_CLOSED", "Session closed"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("product_source_id", models.BigIntegerField(blank=True, null=True)),
                ("variant_source_id", models.BigIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="smart_direct.smartdirectsession",
                    ),
                ),
            ],
            options={
                "db_table": "smart_direct_events",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TemporaryConversationContext",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("recent_messages", models.JSONField(default=list)),
                ("state", models.JSONField(default=dict)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temporary_context",
                        to="smart_direct.smartdirectsession",
                    ),
                ),
            ],
            options={
                "db_table": "smart_direct_temporary_contexts",
            },
        ),
    ]
