# Generated by Django 5.1.7 on 2026-09-20 14:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_direct", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstagramProcessedEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.CharField(max_length=255, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("inbound_message", "Inbound message"),
                            ("outbound_message", "Outbound message"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_instagram_events",
                        to="smart_direct.smartdirectsession",
                    ),
                ),
            ],
            options={
                "db_table": "smart_direct_processed_events",
            },
        ),
        migrations.CreateModel(
            name="SmartDirectRuntimeState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_webhook_at", models.DateTimeField(blank=True, null=True)),
                ("last_webhook_status", models.CharField(blank=True, max_length=32)),
                ("last_webhook_note", models.CharField(blank=True, max_length=128)),
                ("last_send_at", models.DateTimeField(blank=True, null=True)),
                ("last_send_ok", models.BooleanField(blank=True, null=True)),
                ("last_send_error", models.CharField(blank=True, max_length=255)),
                ("last_send_session_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "smart_direct_runtime_state",
            },
        ),
    ]
