# Generated by Django 5.1.7 on 2026-09-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_direct', '0002_instagram_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartdirectevent',
            name='event_type',
            field=models.CharField(choices=[('SESSION_STARTED', 'Session started'), ('PRODUCT_REQUEST', 'Product request'), ('PRODUCT_SUGGESTED', 'Product suggested'), ('PRODUCT_SELECTED', 'Product selected'), ('PRODUCT_LINK_SENT', 'Product link sent'), ('LINK_CLICKED', 'Link clicked'), ('CUSTOMER_MESSAGE_RECEIVED', 'Customer message received'), ('ADMIN_REPLY_SENT', 'Admin reply sent'), ('ADMIN_HANDOFF', 'Admin handoff'), ('SESSION_CLOSED', 'Session closed')], db_index=True, max_length=32),
        ),
    ]
