# Generated by Django 5.1.7 on 2026-09-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.BigIntegerField(unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('mobile', models.CharField(blank=True, db_index=True, max_length=32)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=64)),
                ('national_code', models.CharField(blank=True, max_length=32)),
                ('gender', models.CharField(blank=True, max_length=32)),
                ('first_order_at', models.DateTimeField(blank=True, null=True)),
                ('last_order_at', models.DateTimeField(blank=True, null=True)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('created_at_source', models.DateTimeField(blank=True, null=True)),
                ('updated_at_source', models.DateTimeField(blank=True, null=True)),
                ('source_payload', models.JSONField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['-last_order_at', '-source_id'],
            },
        ),
    ]
