# Generated by Django 5.1.7 on 2026-09-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sync_cursors',
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32)),
                ('status', models.CharField(default='running', max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('window_start', models.DateTimeField(blank=True, null=True)),
                ('window_end', models.DateTimeField(blank=True, null=True)),
                ('requests_made', models.PositiveIntegerField(default=0)),
                ('orders_seen', models.PositiveIntegerField(default=0)),
                ('orders_upserted', models.PositiveIntegerField(default=0)),
                ('customers_upserted', models.PositiveIntegerField(default=0)),
                ('items_upserted', models.PositiveIntegerField(default=0)),
                ('products_upserted', models.PositiveIntegerField(default=0)),
                ('variants_upserted', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('report', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sync_runs',
                'ordering': ['-started_at'],
            },
        ),
    ]
