# Generated by Django 5.1.7 on 2026-09-17 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.BigIntegerField(unique=True)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(blank=True, max_length=64)),
                ('source_payload', models.JSONField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['title', 'source_id'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=512)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('sku', models.CharField(blank=True, max_length=128)),
                ('barcode', models.CharField(blank=True, max_length=128)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('final_price', models.BigIntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('color_name', models.CharField(blank=True, max_length=128)),
                ('size', models.CharField(blank=True, max_length=64)),
                ('source_payload', models.JSONField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='products.product')),
            ],
            options={
                'db_table': 'variants',
            },
        ),
    ]
