# Generated by Django 5.1.7 on 2026-09-17 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.BigIntegerField(unique=True)),
                ('status', models.CharField(db_index=True, max_length=64)),
                ('receiver', models.CharField(blank=True, max_length=255)),
                ('total_amount', models.BigIntegerField(default=0)),
                ('shipping_amount', models.BigIntegerField(default=0)),
                ('discount_amount', models.BigIntegerField(default=0)),
                ('items_count', models.PositiveIntegerField(default=0)),
                ('is_shopino', models.BooleanField(default=False)),
                ('shipping_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('details_synced_at', models.DateTimeField(blank=True, null=True)),
                ('source_payload', models.JSONField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customers.customer')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.BigIntegerField(unique=True)),
                ('product_source_id', models.BigIntegerField(blank=True, null=True)),
                ('variant_source_id', models.BigIntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('amount', models.BigIntegerField(default=0)),
                ('discount_amount', models.BigIntegerField(default=0)),
                ('status', models.IntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('source_payload', models.JSONField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.variant')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
    ]
